/**
 * Example Component: Using Supabase with the useSupabase Hook
 * 
 * This component demonstrates:
 * - Loading announcements from Supabase
 * - Creating new announcements
 * - Searching announcements
 * - Paginating results
 * - Error handling
 */

import { useState, useEffect } from 'react';
import { useSupabase } from '@/lib/use-supabase';
import { Card } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { AlertCircle, Plus, Search, Loader2 } from 'lucide-react';

interface Announcement {
  id: string;
  title: string;
  description: string;
  content?: string;
  posted_by: string;
  created_at: string;
  updated_at: string;
}

export function AnnouncementsExample() {
  // Initialize the Supabase hook for announcements table
  const {
    data: announcements,
    loading,
    error,
    readAll,
    readWhere,
    search: searchAnnouncements,
    create,
  } = useSupabase<Announcement>('announcements');

  const [searchTerm, setSearchTerm] = useState('');
  const [isCreating, setIsCreating] = useState(false);

  // Load announcements on component mount
  useEffect(() => {
    loadAnnouncements();
  }, []);

  const loadAnnouncements = async () => {
    await readAll();
  };

  // Handle search
  const handleSearch = async (term: string) => {
    if (term.trim() === '') {
      await readAll();
    } else {
      await searchAnnouncements('title', term);
    }
  };

  // Handle create new announcement
  const handleCreateAnnouncement = async () => {
    const newAnnouncement = {
      title: 'New Announcement from Portal',
      description: 'This is a test announcement created from the portal',
      content: 'Full content goes here...',
      posted_by: 'admin-user-id', // Should come from auth context
      id: '', // Will be generated by Supabase
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    };

    const result = await create(newAnnouncement);
    if (result) {
      setIsCreating(false);
      // Reload announcements
      await readAll();
    }
  };

  return (
    <div className="space-y-6 p-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row gap-4 items-start sm:items-center justify-between">
        <div>
          <h2 className="text-2xl font-bold">Announcements</h2>
          <p className="text-muted-foreground mt-1">
            {Array.isArray(announcements) ? `${announcements.length} announcements` : 'Loading...'}
          </p>
        </div>
        <Button 
          onClick={handleCreateAnnouncement}
          disabled={isCreating}
          className="gap-2"
        >
          {isCreating ? (
            <>
              <Loader2 className="w-4 h-4 animate-spin" />
              Creating...
            </>
          ) : (
            <>
              <Plus className="w-4 h-4" />
              New Announcement
            </>
          )}
        </Button>
      </div>

      {/* Search Bar */}
      <div className="relative">
        <Search className="absolute left-3 top-3 w-4 h-4 text-muted-foreground" />
        <Input
          placeholder="Search announcements..."
          value={searchTerm}
          onChange={(e) => {
            setSearchTerm(e.target.value);
            handleSearch(e.target.value);
          }}
          className="pl-10"
        />
      </div>

      {/* Error Display */}
      {error && (
        <div className="bg-destructive/10 border border-destructive/50 rounded-lg p-4 flex gap-3">
          <AlertCircle className="w-5 h-5 text-destructive flex-shrink-0 mt-0.5" />
          <div>
            <p className="font-semibold text-destructive">Error loading announcements</p>
            <p className="text-sm text-destructive/80 mt-1">{error}</p>
          </div>
        </div>
      )}

      {/* Loading State */}
      {loading && !Array.isArray(announcements) && (
        <div className="grid gap-4">
          {[...Array(3)].map((_, i) => (
            <Card key={i} className="p-6 animate-pulse">
              <div className="h-6 bg-muted rounded mb-3 w-3/4" />
              <div className="h-4 bg-muted rounded w-full mb-2" />
              <div className="h-4 bg-muted rounded w-5/6" />
            </Card>
          ))}
        </div>
      )}

      {/* Announcements List */}
      {Array.isArray(announcements) && announcements.length > 0 ? (
        <div className="grid gap-4">
          {announcements.map((announcement) => (
            <Card key={announcement.id} className="p-6 hover:shadow-md transition-shadow">
              <div className="flex justify-between items-start gap-4">
                <div className="flex-1">
                  <h3 className="text-lg font-semibold text-foreground">
                    {announcement.title}
                  </h3>
                  <p className="text-muted-foreground mt-2">
                    {announcement.description}
                  </p>
                  {announcement.content && (
                    <p className="text-sm text-muted-foreground mt-3 line-clamp-2">
                      {announcement.content}
                    </p>
                  )}
                  <p className="text-xs text-muted-foreground mt-3">
                    {new Date(announcement.created_at).toLocaleDateString()}
                  </p>
                </div>
              </div>
            </Card>
          ))}
        </div>
      ) : !loading && Array.isArray(announcements) && announcements.length === 0 ? (
        <Card className="p-8 text-center">
          <p className="text-muted-foreground">No announcements found</p>
        </Card>
      ) : null}
    </div>
  );
}

/**
 * Usage in a page:
 * 
 * import { AnnouncementsExample } from '@/components/examples/announcements-example';
 * 
 * export default function AnnouncementsPage() {
 *   return <AnnouncementsExample />;
 * }
 */
