#!/usr/bin/env node

import fs from 'fs';
import path from 'path';
import glob from 'fast-glob';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const MOCKUPS_DIR = 'src/components/mockups';
const GENERATED_MODULE = 'src/.generated/mockup-components.ts';

async function discoverComponents() {
  const files = await glob(`${MOCKUPS_DIR}/**/*.tsx`, {
    cwd: process.cwd(),
    ignore: ['**/_*/**', '**/_*.tsx'],
  });

  return files.map((f) => ({
    globKey: './' + f.slice('src/'.length),
    importPath: path.posix.relative('src/.generated', f),
  }));
}

function generateSource(components) {
  const entries = components
    .map(
      (c) =>
        `  ${JSON.stringify(c.globKey)}: () => import(${JSON.stringify(c.importPath)})`,
    )
    .join(',\n');

  return [
    '// This file is auto-generated by generate-mockups.js.',
    'type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;',
    'export const modules: ModuleMap = {',
    entries,
    '};',
    '',
  ].join('\n');
}

async function main() {
  try {
    const components = await discoverComponents();
    const source = generateSource(components);
    const generatedPath = path.join(process.cwd(), GENERATED_MODULE);

    // Ensure directory exists
    fs.mkdirSync(path.dirname(generatedPath), { recursive: true });

    // Write the generated file
    fs.writeFileSync(generatedPath, source);
    console.log(`Generated mockup components file: ${generatedPath}`);
  } catch (error) {
    console.error('Failed to generate mockup components:', error);
    process.exit(1);
  }
}

main();
